#!/bin/bash
# Claude Code PreToolUse hook
# Auto-generated by Agent Memory
#
# Purpose:
# - Enforce critical guidelines BEFORE running Edit/Write/Bash (blocks on violations)
# - Does not rely on the model remembering to call memory_verify

set -euo pipefail

# Exit early if no stdin (Claude provides hook JSON on stdin)
if [ -t 0 ]; then
  exit 0
fi

# Stable default DB location (can be overridden by env)
if [ -z "${AGENT_MEMORY_DB_PATH:-}" ]; then
  export AGENT_MEMORY_DB_PATH="${HOME}/.agent-memory/memory.db"
fi

# Prefer a locally installed binary; fallback to npx.
if command -v agent-memory >/dev/null 2>&1; then
  AM_CMD=(agent-memory)
else
  AM_CMD=(npx -y agent-memory@latest)
fi

AGENT_ID="${AGENT_ID:-claude-code}"

exec "${AM_CMD[@]}" hook pretooluse --agent-id "${AGENT_ID}"
