#!/bin/bash
# Claude Code SessionEnd hook
# Auto-generated by Agent Memory
#
# Purpose:
# - Ingest Claude transcript into Agent Memory conversation history
# - Prevent "lost information" even if the agent never called memory tools

set -euo pipefail

if [ -t 0 ]; then
  exit 0
fi

if [ -z "${AGENT_MEMORY_DB_PATH:-}" ]; then
  export AGENT_MEMORY_DB_PATH="${HOME}/.agent-memory/memory.db"
fi

if command -v agent-memory >/dev/null 2>&1; then
  AM_CMD=(agent-memory)
else
  AM_CMD=(npx -y agent-memory@latest)
fi

AGENT_ID="${AGENT_ID:-claude-code}"

exec "${AM_CMD[@]}" hook session-end --agent-id "${AGENT_ID}"
