#!/bin/bash
# Claude Code Stop hook
# Auto-generated by Agent Memory
#
# Purpose:
# - Block stopping until end-of-session observe+review is done (or explicitly suspended)
# - Ensures no information is lost due to missed tool calls

set -euo pipefail

if [ -t 0 ]; then
  exit 0
fi

if [ -z "${AGENT_MEMORY_DB_PATH:-}" ]; then
  export AGENT_MEMORY_DB_PATH="${HOME}/.agent-memory/memory.db"
fi

if command -v agent-memory >/dev/null 2>&1; then
  AM_CMD=(agent-memory)
else
  AM_CMD=(npx -y agent-memory@latest)
fi

AGENT_ID="${AGENT_ID:-claude-code}"

exec "${AM_CMD[@]}" hook stop --agent-id "${AGENT_ID}"
