#!/bin/bash
# Claude Code UserPromptSubmit hook
# Auto-generated by Agent Memory
#
# Purpose:
# - Allow per-session review controls via commands like:
#   - !am review off / on
#   - !am review done
#   - !am status

set -euo pipefail

if [ -t 0 ]; then
  exit 0
fi

if [ -z "${AGENT_MEMORY_DB_PATH:-}" ]; then
  export AGENT_MEMORY_DB_PATH="${HOME}/.agent-memory/memory.db"
fi

if command -v agent-memory >/dev/null 2>&1; then
  AM_CMD=(agent-memory)
else
  AM_CMD=(npx -y agent-memory@latest)
fi

exec "${AM_CMD[@]}" hook userpromptsubmit
