#!/bin/bash
# Claude Code post-response verification hook
# Auto-generated by Agent Memory - verifies responses against critical guidelines
#
# Usage: This hook is called automatically after tool calls (Edit, Write, Bash)
# Environment: Requires agent-memory MCP server to be running

# Exit early if no stdin
if [ -t 0 ]; then
  exit 0
fi

# Read the tool output from stdin
TOOL_OUTPUT=$(cat)

# Skip verification for non-file operations
if [ -z "$TOOL_OUTPUT" ]; then
  exit 0
fi

# Check if this is a file modification tool
TOOL_NAME="${CLAUDE_TOOL_NAME:-}"
case "$TOOL_NAME" in
  Edit|Write|Bash)
    # Continue with verification
    ;;
  *)
    # Skip verification for other tools
    exit 0
    ;;
esac

# Extract file path if available
FILE_PATH="${CLAUDE_TOOL_ARG_FILE_PATH:-${CLAUDE_TOOL_ARG_file_path:-}}"

# Build verification request
REQUEST="{
  \"action\": \"post_check\",
  \"sessionId\": \"${CLAUDE_SESSION_ID:-}\",
  \"completedAction\": {
    \"type\": \"file_write\",
    \"filePath\": \"$FILE_PATH\",
    \"content\": $(echo "$TOOL_OUTPUT" | head -c 10000 | jq -Rs .),
    \"description\": \"Tool: $TOOL_NAME\"
  }
}"

# Call verification via local script
# Note: Uses the project's verify-response script
SCRIPT_DIR="$(cd "$(dirname "$0")/../.." && pwd)"
PROJECT_ID="d038447a-57fe-4070-8a6c-f8cd41131099"

# Run verification and capture exit code
cd "$SCRIPT_DIR"
RESULT=$(echo "$TOOL_OUTPUT" | npx tsx scripts/verify-response.ts --json --project-id="$PROJECT_ID" 2>&1)
VERIFY_EXIT=$?

# If verification script exited with 1, it found violations
if [ $VERIFY_EXIT -eq 1 ]; then
  echo "ERROR: Critical guideline violation detected!" >&2
  echo "$RESULT" | grep -A 100 '"violations"' | head -20 >&2
  exit 1
fi

exit 0
