import { basename } from 'node:path';

/**
 * Convert .md to .mdc for Cursor (add frontmatter if missing)
 */
export function convertToMdc(content: string, sourcePath: string): string {
  // Check if content already has frontmatter
  if (content.trim().startsWith('---')) {
    return content;
  }

  // Extract filename without extension for description
  const fileName = basename(sourcePath, '.md');
  const description = fileName.replace(/[-_]/g, ' ');

  // Add basic frontmatter
  return `---
description: ${description}
---

${content}`;
}

/**
 * Concatenate multiple markdown files into a single file for Claude Code
 * Only includes the core file content to keep it lean
 */
export function concatenateForSingleMd(files: Map<string, string>, _ide: string): string {
  const parts: string[] = [
    '# Agent Memory Rules',
    '',
    '> Auto-generated by `npm run sync-rules`. Do not edit directly.',
    '',
    '## Quick Reference',
    '',
    'For detailed information, see the modular rule files in `rules/`:',
    '- `auto-memory-reference.md` - Tool parameters and schemas',
    '- `auto-memory-examples.md` - Usage examples',
    '- `auto-memory-strategies.md` - Optimization strategies',
    '- `auto-memory-advanced.md` - Advanced features',
    '',
  ];

  // Only include core file for Claude (keep it lean, ~400 lines)
  const coreFile = [...files.entries()].find(([name]) => name.includes('core'));

  if (coreFile) {
    let content = coreFile[1];
    // Remove frontmatter if present
    if (content.startsWith('---')) {
      const endIndex = content.indexOf('---', 3);
      if (endIndex !== -1) {
        content = content.slice(endIndex + 3).trim();
      }
    }
    parts.push(content);
  }

  return parts.join('\n');
}

/**
 * Extract raw markdown content from a Cursor `.mdc` file.
 */
export function extractContentFromMdc(content: string): string {
  if (!content.trim().startsWith('---')) return content;
  const endIndex = content.indexOf('---', 3);
  if (endIndex === -1) return content;
  return content.slice(endIndex + 3).trimStart();
}
