#!/usr/bin/env node
/**
 * Agent Memory Setup Command
 *
 * Installs Agent Memory rules to IDE global configurations.
 *
 * Usage:
 *   npx agent-memory setup           # Install to global IDE configs
 *   npx agent-memory setup --project # Install to current project
 *   npx agent-memory setup --ide cursor,claude  # Specific IDEs only
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { join, dirname, basename } from 'node:path';
import { homedir } from 'node:os';
import { fileURLToPath } from 'node:url';

// =============================================================================
// CONFIGURATION
// =============================================================================

interface IDEConfig {
  name: string;
  globalPath: string;
  projectPath: string;
  format: 'mdc' | 'md' | 'single-md';
  extension: string;
  supportsGlobal: boolean;
}

const IDE_CONFIGS: Record<string, IDEConfig> = {
  cursor: {
    name: 'Cursor',
    globalPath: join(homedir(), '.cursor', 'rules'),
    projectPath: '.cursor/rules',
    format: 'mdc',
    extension: '.mdc',
    supportsGlobal: true,
  },
  claude: {
    name: 'Claude Code',
    globalPath: join(homedir(), '.claude'),
    projectPath: '.',
    format: 'single-md',
    extension: '.md',
    supportsGlobal: true,
  },
  antigravity: {
    name: 'Antigravity',
    globalPath: join(homedir(), '.agent', 'rules'),
    projectPath: '.agent/rules',
    format: 'md',
    extension: '.md',
    supportsGlobal: true,
  },
  copilot: {
    name: 'VS Code / Copilot',
    globalPath: '', // No global support
    projectPath: '.github',
    format: 'single-md',
    extension: '.md',
    supportsGlobal: false,
  },
};

// =============================================================================
// HELPERS
// =============================================================================

function findProjectRoot(): string {
  const scriptDir = dirname(fileURLToPath(import.meta.url));
  let currentDir = scriptDir;

  while (currentDir !== '/') {
    const packageJsonPath = join(currentDir, 'package.json');
    if (existsSync(packageJsonPath)) {
      try {
        const pkg = JSON.parse(readFileSync(packageJsonPath, 'utf-8'));
        if (pkg.name === 'agent-memory') {
          return currentDir;
        }
      } catch {
        // Continue searching
      }
    }
    currentDir = dirname(currentDir);
  }

  return scriptDir;
}

function getRulesSourceDir(): string {
  const projectRoot = findProjectRoot();
  return join(projectRoot, 'rules');
}

function isIDEInstalled(ide: string): boolean {
  const config = IDE_CONFIGS[ide];
  if (!config) return false;

  if (!config.supportsGlobal) return true; // Project-only IDEs are always "available"

  // Check if IDE config directory exists
  const parentDir = dirname(config.globalPath);
  return existsSync(parentDir);
}

function getInstalledIDEs(): string[] {
  return Object.keys(IDE_CONFIGS).filter(isIDEInstalled);
}

function loadRulesFiles(sourceDir: string): Map<string, string> {
  const files = new Map<string, string>();

  if (!existsSync(sourceDir)) {
    console.error(`Rules source directory not found: ${sourceDir}`);
    return files;
  }

  const entries = readdirSync(sourceDir, { withFileTypes: true });

  for (const entry of entries) {
    if (entry.isFile() && entry.name.endsWith('.md') && entry.name !== 'README.md') {
      const filePath = join(sourceDir, entry.name);
      const content = readFileSync(filePath, 'utf-8');
      files.set(entry.name, content);
    }
  }

  return files;
}

function convertToMDC(content: string, filename: string): string {
  // Check if already has frontmatter
  if (content.startsWith('---')) {
    // Already has frontmatter, just ensure .mdc extension references
    return content.replace(/\.md"/g, '.mdc"').replace(/\.md\)/g, '.mdc)');
  }

  // Add basic frontmatter
  const name = basename(filename, '.md');
  const frontmatter = `---
description: ${name.replace(/-/g, ' ')}
globs: ["**/*"]
alwaysApply: true
---

`;

  return frontmatter + content;
}

function concatenateForClaude(files: Map<string, string>): string {
  const parts: string[] = [
    '# Agent Memory Rules',
    '',
    '> Auto-generated by `npx agent-memory setup`. Do not edit directly.',
    '',
    '## Quick Reference',
    '',
    'For detailed information, see the modular rule files in `rules/`:',
    '- `auto-memory-reference.md` - Tool parameters and schemas',
    '- `auto-memory-examples.md` - Usage examples',
    '- `auto-memory-strategies.md` - Optimization strategies',
    '- `auto-memory-advanced.md` - Advanced features',
    '',
  ];

  // Only include core file for Claude (keep it lean, ~400 lines)
  // Other files are referenced but not concatenated to avoid bloat
  const coreFile = [...files.entries()].find(([name]) => name.includes('core'));

  if (coreFile) {
    let content = coreFile[1];
    // Remove frontmatter
    if (content.startsWith('---')) {
      const endIndex = content.indexOf('---', 3);
      if (endIndex !== -1) {
        content = content.slice(endIndex + 3).trim();
      }
    }
    parts.push(content);
  }

  return parts.join('\n');
}

function concatenateForCopilot(files: Map<string, string>): string {
  const parts: string[] = [
    '# Copilot Instructions',
    '',
    '> Auto-generated by `npx agent-memory setup`. Do not edit directly.',
    '',
    '## Agent Memory Integration',
    '',
    'This project uses Agent Memory MCP server for persistent context.',
    '',
  ];

  // Only include core file for Copilot (keep it shorter)
  const coreFile = [...files.entries()].find(([name]) => name.includes('core'));

  if (coreFile) {
    let content = coreFile[1];
    // Remove frontmatter
    if (content.startsWith('---')) {
      const endIndex = content.indexOf('---', 3);
      if (endIndex !== -1) {
        content = content.slice(endIndex + 3).trim();
      }
    }
    parts.push(content);
  }

  return parts.join('\n');
}

// =============================================================================
// INSTALLATION
// =============================================================================

interface InstallOptions {
  project: boolean;
  ides: string[];
  quiet: boolean;
  dryRun: boolean;
}

function installForIDE(
  ide: string,
  files: Map<string, string>,
  options: InstallOptions
): { success: boolean; filesWritten: number } {
  const config = IDE_CONFIGS[ide];
  if (!config) {
    console.error(`Unknown IDE: ${ide}`);
    return { success: false, filesWritten: 0 };
  }

  // Determine target directory
  let targetDir: string;
  if (options.project) {
    targetDir = join(process.cwd(), config.projectPath);
  } else {
    if (!config.supportsGlobal) {
      if (!options.quiet) {
        console.log(
          `  ⚠ ${config.name} only supports project-level rules, skipping global install`
        );
      }
      return { success: true, filesWritten: 0 };
    }
    targetDir = config.globalPath;
  }

  // Create directory if needed
  if (!options.dryRun && !existsSync(targetDir)) {
    mkdirSync(targetDir, { recursive: true });
  }

  let filesWritten = 0;

  if (config.format === 'single-md') {
    // Concatenate all files into one
    const targetFile =
      ide === 'claude' ? join(targetDir, 'CLAUDE.md') : join(targetDir, 'copilot-instructions.md');

    const content = ide === 'claude' ? concatenateForClaude(files) : concatenateForCopilot(files);

    if (!options.quiet) {
      console.log(`  → ${targetFile}`);
    }

    if (!options.dryRun) {
      writeFileSync(targetFile, content, 'utf-8');
    }
    filesWritten = 1;
  } else {
    // Write individual files
    for (const [filename, content] of files) {
      const baseName = basename(filename, '.md');
      const targetFile = join(targetDir, baseName + config.extension);

      let finalContent = content;
      if (config.format === 'mdc') {
        finalContent = convertToMDC(content, filename);
      }

      if (!options.quiet) {
        console.log(`  → ${targetFile}`);
      }

      if (!options.dryRun) {
        writeFileSync(targetFile, finalContent, 'utf-8');
      }
      filesWritten++;
    }
  }

  return { success: true, filesWritten };
}

// =============================================================================
// CLI
// =============================================================================

function parseArgs(): InstallOptions {
  const args = process.argv.slice(2);
  const options: InstallOptions = {
    project: false,
    ides: [],
    quiet: false,
    dryRun: false,
  };

  for (let i = 0; i < args.length; i++) {
    const arg = args[i];

    switch (arg) {
      case '--project':
      case '-p':
        options.project = true;
        break;
      case '--ide':
        const ideList = args[++i];
        if (ideList) {
          options.ides = ideList.split(',').map((s) => s.trim().toLowerCase());
        }
        break;
      case '--quiet':
      case '-q':
        options.quiet = true;
        break;
      case '--dry-run':
        options.dryRun = true;
        break;
      case '--help':
      case '-h':
        printHelp();
        process.exit(0);
        break;
      case 'setup':
        // Ignore 'setup' argument (it's the command name)
        break;
      default:
        if (arg.startsWith('-')) {
          console.error(`Unknown option: ${arg}`);
          process.exit(1);
        }
    }
  }

  return options;
}

function printHelp() {
  console.log(`
Agent Memory Setup

Installs Agent Memory rules to your IDE(s) for automatic AI assistant integration.

Usage:
  npx agent-memory setup [options]

Options:
  --project, -p     Install to current project instead of global
  --ide <list>      Comma-separated list of IDEs (cursor,claude,antigravity,copilot)
  --quiet, -q       Suppress output
  --dry-run         Show what would be installed without writing files
  --help, -h        Show this help

Examples:
  npx agent-memory setup                    # Install globally to all detected IDEs
  npx agent-memory setup --project          # Install to current project
  npx agent-memory setup --ide cursor,claude  # Install only to Cursor and Claude
  npx agent-memory setup --dry-run          # Preview installation

Supported IDEs:
  cursor       - Cursor IDE (~/.cursor/rules/)
  claude       - Claude Code (~/.claude/CLAUDE.md)
  antigravity  - Antigravity (~/.agent/rules/)
  copilot      - VS Code / Copilot (.github/copilot-instructions.md) - project only
`);
}

async function main() {
  const options = parseArgs();

  // Load rules files
  const sourceDir = getRulesSourceDir();
  const files = loadRulesFiles(sourceDir);

  if (files.size === 0) {
    console.error('No rules files found in:', sourceDir);
    process.exit(1);
  }

  // Determine which IDEs to install to
  let targetIDEs: string[];
  if (options.ides.length > 0) {
    targetIDEs = options.ides;
  } else {
    targetIDEs = getInstalledIDEs();
    // For global install, filter to only those that support global
    if (!options.project) {
      targetIDEs = targetIDEs.filter((ide) => IDE_CONFIGS[ide].supportsGlobal);
    }
  }

  if (targetIDEs.length === 0) {
    console.error('No supported IDEs found. Use --ide to specify manually.');
    process.exit(1);
  }

  // Header
  if (!options.quiet) {
    console.log('');
    console.log('Agent Memory Setup');
    console.log('==================');
    console.log('');
    console.log(`Mode: ${options.project ? 'Project' : 'Global'}`);
    console.log(`Rules: ${files.size} files from ${sourceDir}`);
    console.log(`IDEs: ${targetIDEs.join(', ')}`);
    if (options.dryRun) {
      console.log('(Dry run - no files will be written)');
    }
    console.log('');
  }

  // Install to each IDE
  let totalFiles = 0;
  let successCount = 0;

  for (const ide of targetIDEs) {
    const config = IDE_CONFIGS[ide];
    if (!config) {
      console.error(`Unknown IDE: ${ide}`);
      continue;
    }

    if (!options.quiet) {
      console.log(`${config.name}:`);
    }

    const result = installForIDE(ide, files, options);
    if (result.success) {
      successCount++;
      totalFiles += result.filesWritten;
    }

    if (!options.quiet) {
      console.log('');
    }
  }

  // Summary
  if (!options.quiet) {
    console.log('---');
    console.log(`Done! Installed ${totalFiles} file(s) to ${successCount} IDE(s).`);

    if (!options.project) {
      console.log('');
      console.log('Rules are now active globally. Restart your IDE to apply.');
      console.log('');
      console.log('To install project-specific rules instead:');
      console.log('  npx agent-memory setup --project');
    }
  }
}

main().catch((error) => {
  console.error('Setup failed:', error);
  process.exit(1);
});
